# Generated by Django 5.2.13 on 2026-04-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_roomvideo_creator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomvideo',
            name='room_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
