# Generated by Django 5.2.13 on 2026-04-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_roomvideo_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomvideo',
            name='invite_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
