# Generated by Django 5.2.13 on 2026-04-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_roomvideo_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomvideo',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
