# Generated by Django 5.2.14 on 2026-05-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_roomvideo_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_type',
            field=models.CharField(choices=[('FILE', 'Local File'), ('YOUTUBE', 'YouTube Video')], default='FILE', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='movies/videos/'),
        ),
    ]
