# Generated by Django 5.2.14 on 2026-06-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_video_type_movie_youtube_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomvideo',
            name='creator_name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomvideo',
            name='invite_code',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomvideo',
            name='room_name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
