sonar.projectKey=snikers02_cinema-backend
sonar.organization=snikers02

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=cinema-backend
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# This property is optional if sonar.modules is set.
sonar.sources=.

# Exclude files from analysis
sonar.exclusions=**/migrations/**, **/tests/**, venv/**, .venv/**, .github/**

# Python configuration
sonar.python.version=3.12
