# Generated by Django 5.2.14 on 2026-05-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_alter_roomplaybackstate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomplaybackstate',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
