# Generated by Django 5.2.14 on 2026-05-19 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_alter_roomplaybackstate_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPlaybackRules',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_id', models.UUIDField(unique=True)),
                ('anyone_can_control', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomAuthorizedController',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_id', models.UUIDField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_room_controls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('room_id', 'user')},
            },
        ),
    ]
