# Generated by Django 5.2.13 on 2026-04-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='Default Room', max_length=255),
            preserve_default=False,
        ),
    ]
