# Generated by Django 5.2.13 on 2026-04-27 19:40

from django.db import migrations, models
import random
import string


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_name'),
    ]

    def _generate_invite_code():
        return ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))

    def backfill_invite_codes(apps, schema_editor):
        Room = apps.get_model('rooms', 'Room')

        # Fill existing rows first, before adding UNIQUE constraint.
        for room in Room.objects.all().only('id', 'invite_code'):
            if room.invite_code:
                continue

            code = Migration._generate_invite_code()
            while Room.objects.filter(invite_code=code).exists():
                code = Migration._generate_invite_code()

            Room.objects.filter(id=room.id).update(invite_code=code)

    operations = [
        migrations.AddField(
            model_name='room',
            name='invite_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.RunPython(backfill_invite_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='room',
            name='invite_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, unique=True),
        ),
    ]
